### ISSUE TITLE
use Paths for cross-platform file paths

### ISSUE THREAD

**Issue by KrabCode** [KrabCode/LazyGui#248]
autosave has been fixed in a recent pull request, I'll fix the other ones

**Comment by KrabCode** [comment]
official release will have to wait until the weekend when I get around to building and deploying it, but this should already work in IntelliJ - the manual integer named saves (Ctrl+S) should now be fixed too.

**Comment by KrabCode** [comment]
@pflouret since this is related to your recent pull request, would you be so kind as to try if this doesn't completely break it for you? :) thanks a lot

heads up, it's just on the develop branch for now, will merge to master before release

**Comment by pflouret** [comment]
Nothing breaks for me, but it looks like you missed one here 😊 https://github.com/KrabCode/LazyGui/blob/27239dee98ee584dc5d2ea8757ca5a4eb035e3e6/src/main/java/com/krab/lazy/LazyGui.java#L1215

Thanks for taking care of this!

**Comment by KrabCode** [comment]
the fix is released now in v1.2.1
